language: php
sudo: false
php:
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"

before_install:
 - curl -sS https://getcomposer.org/installer | php

before_script:
 - php composer.phar install --prefer-dist --dev

script:
 - phpunit
